/**
 * Landmark Mapping Validation Tool
 * 
 * Validates or creates landmark-to-model vertex mapping file.
 * This replaces the Python MappingSetupStep logic.
 * 
 * Usage:
 *   build/bin/validate_mapping --mapping <path> --model-dir <path> [--min-count <n>] [--create-default]
 * 
 * Example:
 *   build/bin/validate_mapping --mapping data/landmark_mapping.txt --model-dir data/model_biwi --min-count 15
 */

#include "model/MorphableModel.h"
#include "alignment/LandmarkMapping.h"
#include <iostream>
#include <iomanip>
#include <string>
#include <vector>
#include <fstream>
#include <map>

using namespace face_reconstruction;

int main(int argc, char* argv[]) {
    std::string mapping_path;
    std::string model_dir;
    int min_count = 15;
    bool create_default = false;
    
    // Parse arguments
    for (int i = 1; i < argc; ++i) {
        std::string arg = argv[i];
        if (arg == "--mapping" && i + 1 < argc) {
            mapping_path = argv[++i];
        } else if (arg == "--model-dir" && i + 1 < argc) {
            model_dir = argv[++i];
        } else if (arg == "--min-count" && i + 1 < argc) {
            min_count = std::stoi(argv[++i]);
        } else if (arg == "--create-default") {
            create_default = true;
        } else if (arg == "--help") {
            std::cerr << "Usage: " << argv[0] 
                      << " --mapping <path> --model-dir <path> [--min-count <n>] [--create-default]" << std::endl;
            return 1;
        }
    }
    
    if (mapping_path.empty() || model_dir.empty()) {
        std::cerr << "Error: --mapping and --model-dir are required" << std::endl;
        return 1;
    }
    
    // Load model to validate vertex indices
    MorphableModel model;
    if (!model.loadFromFiles(model_dir)) {
        std::cerr << "Error: Failed to load model from " << model_dir << std::endl;
        return 1;
    }
    
    // Try to load existing mapping
    LandmarkMapping mapping;
    bool mapping_exists = mapping.loadFromFile(mapping_path);
    
    if (mapping_exists) {
        // Validate existing mapping
        std::vector<int> mapped_landmarks = mapping.getMappedLandmarks();
        int valid_count = 0;
        
        for (int lm_idx : mapped_landmarks) {
            int vtx_idx = mapping.getModelVertex(lm_idx);
            if (vtx_idx >= 0 && vtx_idx < model.num_vertices) {
                valid_count++;
            }
        }
        
        if (valid_count >= min_count) {
            std::cout << "OK " << valid_count << std::endl;
            return 0;
        } else {
            std::cerr << "ERROR: Mapping has only " << valid_count 
                      << " valid entries (minimum: " << min_count << ")" << std::endl;
            return 1;
        }
    } else if (create_default) {
        // Create default mapping
        std::ofstream file(mapping_path);
        if (!file.is_open()) {
            std::cerr << "Error: Failed to create mapping file: " << mapping_path << std::endl;
            return 1;
        }
        
        file << "# Landmark to Model Vertex Mapping\n";
        file << "# Format: landmark_index model_vertex_index\n";
        file << "# Generated by validate_mapping\n\n";
        
        // Default mapping pairs
        std::vector<std::pair<int, int>> default_pairs = {
            {4, 700},   // Left jaw
            {8, 810},   // Chin
            {12, 903},  // Right jaw
            {30, 125},  // Nose tip
            {36, 262},  // Left eye corner
            {45, 126},  // Right eye corner
            {48, 374},  // Left mouth corner
            {54, 51},   // Right mouth corner
        };
        
        for (const auto& pair : default_pairs) {
            if (pair.second < model.num_vertices) {
                file << pair.first << " " << pair.second << "\n";
            }
        }
        
        file.close();
        std::cout << "CREATED " << default_pairs.size() << std::endl;
        return 0;
    } else {
        std::cerr << "ERROR: Mapping file not found: " << mapping_path << std::endl;
        return 1;
    }
}

