/**
 * Landmark Mapping Validation Tool
 * 
 * Validates or creates landmark-to-model vertex mapping file.
 * This replaces the Python MappingSetupStep logic.
 * 
 * Usage:
 *   build/bin/validate_mapping --mapping <path> --model-dir <path> [--min-count <n>] [--create-default]
 * 
 * Example:
 *   build/bin/validate_mapping --mapping data/landmark_mapping.txt --model-dir data/model_biwi --min-count 15
 */

#include "model/MorphableModel.h"
#include "alignment/LandmarkMapping.h"
#include <iostream>
#include <iomanip>
#include <string>
#include <vector>
#include <fstream>
#include <map>

using namespace face_reconstruction;

int main(int argc, char* argv[]) {
    std::string mapping_path;
    std::string model_dir;
    int min_count = 15;
    bool create_default = false;
    
    // Parse arguments
    for (int i = 1; i < argc; ++i) {
        std::string arg = argv[i];
        if (arg == "--mapping" && i + 1 < argc) {
            mapping_path = argv[++i];
        } else if (arg == "--model-dir" && i + 1 < argc) {
            model_dir = argv[++i];
        } else if (arg == "--min-count" && i + 1 < argc) {
            min_count = std::stoi(argv[++i]);
        } else if (arg == "--create-default") {
            create_default = true;
        } else if (arg == "--help") {
            std::cerr << "Usage: " << argv[0] 
                      << " --mapping <path> --model-dir <path> [--min-count <n>] [--create-default]" << std::endl;
            return 1;
        }
    }
    
    if (mapping_path.empty() || model_dir.empty()) {
        std::cerr << "Error: --mapping and --model-dir are required" << std::endl;
        return 1;
    }
    
    // Load model to validate vertex indices
    MorphableModel model;
    if (!model.loadFromFiles(model_dir)) {
        std::cerr << "Error: Failed to load model from " << model_dir << std::endl;
        return 1;
    }
    
    // Try to load existing mapping
    LandmarkMapping mapping;
    bool mapping_exists = mapping.loadFromFile(mapping_path);
    
    if (mapping_exists) {
        // Validate existing mapping
        std::vector<int> mapped_landmarks = mapping.getMappedLandmarks();
        int valid_count = 0;
        
        for (int lm_idx : mapped_landmarks) {
            int vtx_idx = mapping.getModelVertex(lm_idx);
            if (vtx_idx >= 0 && vtx_idx < model.num_vertices) {
                valid_count++;
            }
        }
        
        if (valid_count >= min_count) {
            std::cout << "OK " << valid_count << std::endl;
            return 0;
        } else {
            std::cerr << "ERROR: Mapping has only " << valid_count 
                      << " valid entries (minimum: " << min_count << ")" << std::endl;
            return 1;
        }
    } else if (create_default) {
        // Create default mapping
        std::ofstream file(mapping_path);
        if (!file.is_open()) {
            std::cerr << "Error: Failed to create mapping file: " << mapping_path << std::endl;
            return 1;
        }
        
        file << "# Landmark to Model Vertex Mapping\n";
        file << "# Format: landmark_index model_vertex_index\n";
        file << "# Auto-generated by validate_mapping (30 default mappings)\n\n";
        
        // Default mapping pairs (30 landmarks covering key facial features)
        // Based on dlib 68-point model, distributed across:
        // - Jawline (0-16): 9 points
        // - Eyebrows (17-26): 6 points
        // - Nose (27-35): 5 points
        // - Eyes (36-47): 10 points
        // - Mouth (48-67): 7 points
        // 
        // Vertex indices are distributed across the model based on typical face mesh structure
        // For a model with N vertices, we use indices that are likely to be in facial regions
        int num_vertices = model.num_vertices;
        
        // Calculate vertex indices as percentages of model size
        // These are approximate and may need adjustment based on actual model structure
        std::vector<std::pair<int, int>> default_pairs = {
            // Jawline (9 points) - lower face region (roughly 60-90% of model)
            {0, static_cast<int>(num_vertices * 0.60)},   // Left jaw start
            {2, static_cast<int>(num_vertices * 0.63)},   // Left jaw
            {4, static_cast<int>(num_vertices * 0.66)},   // Left jaw mid
            {6, static_cast<int>(num_vertices * 0.70)},   // Left jaw lower
            {8, static_cast<int>(num_vertices * 0.75)},   // Chin center
            {10, static_cast<int>(num_vertices * 0.80)},  // Right jaw lower
            {12, static_cast<int>(num_vertices * 0.83)},  // Right jaw mid
            {14, static_cast<int>(num_vertices * 0.86)},  // Right jaw
            {16, static_cast<int>(num_vertices * 0.90)},  // Right jaw end
            
            // Right eyebrow (3 points) - upper face region (roughly 20-30% of model)
            {17, static_cast<int>(num_vertices * 0.20)},  // Right eyebrow outer
            {19, static_cast<int>(num_vertices * 0.23)},  // Right eyebrow mid
            {21, static_cast<int>(num_vertices * 0.26)},  // Right eyebrow inner
            
            // Left eyebrow (3 points) - upper face region
            {22, static_cast<int>(num_vertices * 0.27)},  // Left eyebrow inner
            {24, static_cast<int>(num_vertices * 0.30)},  // Left eyebrow mid
            {26, static_cast<int>(num_vertices * 0.33)},  // Left eyebrow outer
            
            // Nose (5 points) - center face region (roughly 40-50% of model)
            {27, static_cast<int>(num_vertices * 0.40)},  // Nose top
            {30, static_cast<int>(num_vertices * 0.45)},  // Nose tip
            {31, static_cast<int>(num_vertices * 0.46)},  // Nose bottom left
            {33, static_cast<int>(num_vertices * 0.47)},  // Nose bottom center
            {35, static_cast<int>(num_vertices * 0.48)},  // Nose bottom right
            
            // Right eye (5 points) - mid-upper face region (roughly 25-35% of model)
            {36, static_cast<int>(num_vertices * 0.25)},  // Right eye outer corner
            {37, static_cast<int>(num_vertices * 0.28)},  // Right eye top
            {39, static_cast<int>(num_vertices * 0.30)},  // Right eye center
            {40, static_cast<int>(num_vertices * 0.32)},  // Right eye bottom
            {41, static_cast<int>(num_vertices * 0.34)},  // Right eye inner corner
            
            // Left eye (5 points) - mid-upper face region
            {42, static_cast<int>(num_vertices * 0.35)},  // Left eye inner corner
            {43, static_cast<int>(num_vertices * 0.37)},  // Left eye bottom
            {45, static_cast<int>(num_vertices * 0.39)},  // Left eye center
            {46, static_cast<int>(num_vertices * 0.41)},  // Left eye top
            {47, static_cast<int>(num_vertices * 0.43)},  // Left eye outer corner
            
            // Mouth (7 points) - lower-mid face region (roughly 50-60% of model)
            {48, static_cast<int>(num_vertices * 0.50)},  // Left mouth corner
            {51, static_cast<int>(num_vertices * 0.52)},  // Top lip left
            {54, static_cast<int>(num_vertices * 0.54)},  // Right mouth corner
            {57, static_cast<int>(num_vertices * 0.56)},  // Top lip right
            {60, static_cast<int>(num_vertices * 0.58)},  // Bottom lip center
            {64, static_cast<int>(num_vertices * 0.59)},  // Bottom lip left
            {67, static_cast<int>(num_vertices * 0.60)},  // Bottom lip right
        };
        
        int valid_count = 0;
        for (const auto& pair : default_pairs) {
            if (pair.second < model.num_vertices) {
                file << pair.first << " " << pair.second << "\n";
                valid_count++;
            }
        }
        
        file.close();
        
        if (valid_count < min_count) {
            std::cerr << "WARNING: Only " << valid_count << " valid mappings created (minimum: " << min_count << ")" << std::endl;
            std::cerr << "Model has " << model.num_vertices << " vertices. Some default vertex indices may be out of range." << std::endl;
            std::cerr << "Consider using a heuristic mapping tool or manually creating the mapping file." << std::endl;
        }
        
        std::cout << "CREATED " << valid_count << std::endl;
        return 0;
    } else {
        std::cerr << "ERROR: Mapping file not found: " << mapping_path << std::endl;
        return 1;
    }
}

